// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqvkqkmvyrqnoxxxigyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdmtxa212eXJxbm94eHhpZ3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzA2OTQsImV4cCI6MjA2MjcwNjY5NH0.aPxrQ6OvtYJdW7zD5YxjgyVg11Z4IIL361Em418EOTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);